import Head from "next/head";
import styles from "../styles/Home.module.css";
import { Box, Button } from "@chakra-ui/react";
import Link from "next/link";

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Stephane Guichard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box>
				<Box textStyle="h1">Stéphane Guichard</Box>
				<Box> Software and Data engineer</Box>
				<Link href="https://www.linkedin.com/in/steph-guichard/">
					<Button mt={4}>Linkedin</Button>
				</Link>
			</Box>
		</div>
	);
}
