import Head from "next/head";

import { Box, Button, useColorMode, Flex, Switch } from "@chakra-ui/react";
import Link from "next/link";
import Resume from "components/Resume";

export default function Home() {
	const { colorMode, toggleColorMode } = useColorMode();
	return (
		<>
			<Head>
				<title>Stephane Guichard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Box bg={colorMode === "light" ? "white" : "black"} minH="100vh">
				<Flex justify="center" align="center" position="fixed" mt={2} right={5}>
					<Box color="centralGrey" mr={4}>
						{colorMode === "light" ? "☀" : "🌒"}
					</Box>
					<Switch
						onChange={toggleColorMode}
						isChecked={colorMode === "dark"}
						size="md"
					/>
				</Flex>
				<Box
					display="flex"
					justifyContent="center"
					alignItems="center"
					minH="100vh"
					px={[8, 4]}
				>
					<Box maxW={"98vw"}>
						<Box mt={["50vw", "20vw", "10vw"]}>
							<Box textStyle="h1">Stéphane Guichard</Box>
							<Box> Software and Data engineer</Box>
							<Box>
								<Link href="https://twitter.com/StephaneGch">
									<Button
										borderColor="#00acee"
										color="#00acee"
										mt={4}
										variant="outlined"
									>
										Twitter
									</Button>
								</Link>
								<Link href="https://www.linkedin.com/in/steph-guichard/">
									<Button mt={4} mx={2}>
										Linkedin
									</Button>
								</Link>
							</Box>
						</Box>
						<Resume />
					</Box>
				</Box>
			</Box>
		</>
	);
}
