import Head from "next/head";

import { Box, Button, useColorMode } from "@chakra-ui/react";
import Link from "next/link";
import Navbar from "components/Navbar";

export default function Home() {
	const { colorMode } = useColorMode();
	return (
		<>
			<Head>
				<title>MarryMe.network</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<Box
				bg={colorMode === "light" ? "white" : "black"}
				transition="background-color 0.3s"
				minH="100vh"
			>
				<Box
					display="flex"
					justifyContent="center"
					alignItems="center"
					minH="100vh"
					px={[8, 4]}
				>
					<Box maxW={"98vw"}>
						<Box>
							<Box
								textStyle="h1"
								bgGradient="linear-gradient(90deg, rgba(238,174,202,1) 0%, rgba(148,187,233,1) 100%);"
								bgClip="text"
							>
								MarryMe.network
							</Box>
							<Box textStyle="h2" mt={2}>
								An eternal and immutable mariage contract, on chain.
							</Box>
							<Box></Box>
						</Box>
						{/* <Resume /> */}
						<Box
							position="absolute"
							bottom={2}
							left={2}
							textStyle="small"
							display="flex"
							flexDirection="row"
							alignItems="baseline"
						>
							Stéphane Guichard © 2022 - me@stephane.pro{" "}
							<Link href="https://twitter.com/StephaneGch">
								<Button
									borderColor="rgba(252,70,107,1)"
									color="rgba(252,70,107,1)"
									ml={4}
									variant="outlined"
									size="xs"
								>
									Twitter
								</Button>
							</Link>
						</Box>
					</Box>
				</Box>
			</Box>
		</>
	);
}
